Custom notifications
ControlPanel-gg/dashboard pull request #160
Opened 2021-08-02 22:23 UTC by j122j

This pull request adds custom notifications.
Both website and email notifications can be sent using the admin dashboard or using API.

Checklist:
- [ ] Add admin UI.
- [x] Add API endpoints.

API Endpoints:
- GET /notifications/{user}
- GET /notifications/{user}/{notification}
- POST /notifications/{user}
- DELETE /notifications/{user}
- DELETE /notifications/{user}/{notification}

Closes #142 #106

2021-08-04 21:18 UTC, j122j commented
Admin UI Preview
![5014417d](https://user-images.githubusercontent.com/34238819/128256227-7ccd0cd5-f0c1-438d-9ffb-c740174ddd27.png)

2021-08-08 08:40 UTC, AVMG20 requested changes
Excellent PR, 2 minor issues but overall very good code base and functionality.

2021-08-08 08:40 UTC, AVMG20 commented on resources/views/admin/users/notifications.blade.php
> +                                           type="checkbox"
add value="1" so the bool validation works

2021-08-08 08:40 UTC, AVMG20 commented on resources/views/admin/users/notifications.blade.php
> +                            <form action="{{route('admin.users.notifications')}}" method="POST">
form tag is not closed

2021-08-08 14:05 UTC, merged