Show Client running out of Credits in Admin overview
ControlPanel-gg/dashboard pull request #276
Opened 2021-11-08 10:52 UTC by 1day2die

Dont know if this is needed, but its kinda a "funny to know" piece of information

![image](https://user-images.githubusercontent.com/8725848/140729585-47adb364-4b01-4ac9-99c7-1e44db94cc3a.png)

2021-11-08 13:52 UTC, anondev-sudo commented
When user ran out of credits, should be displayed

2021-11-11 14:29 UTC, AVMG20 requested changes

2021-11-11 14:29 UTC, AVMG20 commented on app/Models/User.php
> +    public function outOfCredits()
purchase phpstorm or install a beutify plugin :)

2021-11-11 14:34 UTC, 1day2die commented on app/Models/User.php
> +    public function outOfCredits()
DocBlock or Formatting ?

2021-11-12 17:40 UTC, AVMG20 requested changes

2021-11-12 17:40 UTC, AVMG20 commented on app/Models/User.php
> +     * @return string
what's going on here

2021-11-12 18:55 UTC, merged

2021-11-13 13:29 UTC, anondev-sudo commented
I don't see it
![image](https://user-images.githubusercontent.com/85408287/141645591-dab461c1-5f20-471f-9178-939a04a94c07.png)