fix: 🚑️ swapped nodes/eggs column naming -> now correct order
ControlPanel-gg/dashboard pull request #317
Opened 2021-11-29 08:25 UTC by IceToast

Fixed the column naming (nodes & eggs) in the products data table

![image](https://user-images.githubusercontent.com/54889359/143832303-dab026ff-4807-454d-8c07-3992cd67f936.png)

2021-12-01 14:27 UTC, 1day2die approved these changes

2021-12-13 11:42 UTC, 1day2die requested changes

2021-12-13 11:42 UTC, 1day2die commented on resources/views/admin/products/index.blade.php
> +                    [2, "asc"]
Please bring that into the old format

2021-12-14 14:18 UTC, IceToast commented on resources/views/admin/products/index.blade.php
> +                    [2, "asc"]
´done

2021-12-14 14:22 UTC, merged