feat: ✨ Add api routes for suspending and unsuspending an User
ControlPanel-gg/dashboard pull request #362
Opened 2022-01-03 21:16 UTC by LogischJo

This Pull Request adresses the issue #359

2022-01-05 17:06 UTC, BolverBlitz requested changes

2022-01-05 17:06 UTC, BolverBlitz commented on app/Http/Controllers/Api/UserController.php
> +     * Suspends the user
*Unsuspends

2022-01-05 17:07 UTC, LogischJo commented on app/Http/Controllers/Api/UserController.php
> +     * Suspends the user
true lol

2022-01-14 09:17 UTC, 1day2die commented
is this tested @BolverBlitz ?

2022-01-14 13:33 UTC, LogischJo commented
It worked on my System using the at that time latest development version. But you should test it, because 2 tests are better than just one test.

2022-01-14 14:03 UTC, BolverBlitz commented
Works on fresh dev branch pull + this pr.

2022-01-14 18:24 UTC, merged